name: subtitle_wrapper_package
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
version: 1.0.4
homepage: https://github.com/Joran-Dob/flutter_subtitle_wrapper
publish_to: none

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  jidoujisho:
    path: ../
  mecab_dart:
    git:
      url: https://github.com/lrorpilla/mecab_dart
      ref: a822b1ac54ce1fbde33ca7d445c1bfd7dd51ae7c
  bloc: ^6.1.0
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  http: ^0.12.2
  http_parser: ^3.1.4
  ve_dart:
    git:
      url: https://github.com/lrorpilla/ve_dart
      ref: ab4fb0f32a99a324c2c3f6aa04ab03701bf617ad
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.2
  pedantic: ^1.10.0-nullsafety.2
  video_player: ^2.0.0-nullsafety.2
flutter:
