name: jidoujisho
description: A mobile video player tailored for Japanese language learners. 
publish_to: none

version: 0.9.4+beta

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers:
  async:
  chewie:
    path: ./chewie
  clipboard_monitor: ^0.9.1
  device_info:
  ext_storage:
  #file_picker:
  gx_file_picker:
  flutter_ffmpeg:
  flutter_vlc_player:
  fuzzy:
  intl:
  http:
  mecab_dart: ^0.1.2
  package_info: ^0.4.3+4
  path_provider:
  permission_handler:
  scrollable_positioned_list: ^0.1.9
  shared_preferences:
  subtitle_wrapper_package:
    path: ./subtitle_wrapper_package
  transparent_image: ^1.0.0
  unofficial_jisho_api: ^1.1.0
  url_launcher:
  ve_dart: ^0.2.1
  xml2json:
  youtube_explode_dart:
    git:
      url: https://github.com/Hexer10/youtube_explode_dart
      ref: 5385ba1628c109312fc452162e32ebc20961b1dd
  youtube_player_flutter:
  wakelock:

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/ipadic/