name: yuuna
description: A mobile language learning toolkit.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  audio_service: ^0.18.7
  audio_session: ^0.1.10
  blurrycontainer:
    git:
      url: https://github.com/Krish-Ideausher/blurry_container/
      ref: fb26dd1fa81edeb048b14703f1c1f28e93ee43d0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  change_notifier_builder: ^1.1.2
  characters: ^1.2.0
  clipboard: ^0.1.3
  crop_image: ^1.0.2
  device_info_plus: ^3.2.3
  expandable: ^5.0.1
  external_app_launcher: ^2.0.2
  external_path: ^1.0.1
  file_picker: ^4.5.1
  filesystem_picker:
    git:
      url: https://github.com/lrorpilla/filesystem_picker
      ref: c0f132e44d2b5387b4babf8a09b7caf257259313
      path: package
  firebase_crashlytics: ^2.8.1
  float_column: ^1.2.1
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_cache_manager: ^3.3.0
  flutter_colorpicker: ^1.0.3
  flutter_ffmpeg: ^0.4.2
  flutter_inappwebview: ^5.4.3+7
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1
  flutter_process_text: ^1.1.2
  flutter_reorderable_list: ^1.2.0
  flutter_riverpod: ^1.0.4
  flutter_screenutil: ^5.3.1
  flutter_vlc_player: ^7.1.5
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  infinite_carousel: ^1.0.2
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  json_annotation: ^4.5.0
  json_serializable: ^6.1.5
  just_audio: ^0.9.21
  kana_kit: ^2.0.0
  local_assets_server: ^2.0.2+12
  marquee: ^2.2.3
  material_floating_search_bar: 
    git:
      url: https://github.com/lrorpilla/material_floating_search_bar
      ref: main
  mecab_dart: ^0.1.3
  multi_value_listenable_builder: ^0.0.2
  network_to_file_image: ^4.0.1
  nowplaying: ^2.0.6
  package_info_plus: ^1.4.0
  path: ^1.8.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  photo_gallery: ^1.1.1
  pretty_json: ^2.0.0
  progress_indicators: ^1.0.0
  receive_intent: ^0.2.2
  receive_sharing_intent: ^1.4.5
  reorderables: ^0.5.0
  restart_app: ^1.1.0+1
  ruby_text: ^3.0.1
  scrollable_positioned_list: ^0.3.2
  settings_ui: ^2.0.2
  share_plus: ^4.0.4
  spaces:
    git:
      url: https://github.com/triskell/spaces
      ref: master
  subtitle:
    git:
      url: https://github.com/lrorpilla/subtitle
      ref: 9c5307d1cbe3a9ca84c387e2023251896c9ff47f
  tabbed_view: ^1.12.0
  transparent_image: ^2.0.0
  twitter_api_v2: ^2.4.2
  twitter_login: ^4.2.3
  url_launcher: ^6.0.20
  ve_dart:
    git:
      url: https://github.com/lrorpilla/ve_dart
      ref: c366bb1ae24f6fad4f5c7e3a1efad5f2b8122e58
  wakelock: ^0.6.1+2
  youtube_explode_dart: ^1.12.0

dependency_overrides:
  freezed_annotation: ^2.1.0 # Caused by spaces

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^2.2.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/meta/icon.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/meta/icon-android12.png"

flutter:
  uses-material-design: true

  assets:
    - assets/meta/
    - assets/language/japanese/ipadic/
    - assets/ttu-ebook-reader/
    - assets/ttu-ebook-reader/_app/
    - assets/ttu-ebook-reader/_app/immutable/
    - assets/ttu-ebook-reader/_app/immutable/assets/
    - assets/ttu-ebook-reader/_app/immutable/assets/pages/
    - assets/ttu-ebook-reader/_app/immutable/assets/pages/b/
    - assets/ttu-ebook-reader/_app/immutable/chunks/
    - assets/ttu-ebook-reader/_app/immutable/pages/
    - assets/ttu-ebook-reader/_app/immutable/pages/b/
    - assets/ttu-ebook-reader/_app/immutable/pages/manage/
    - assets/ttu-ebook-reader/_app/immutable/pages/settings/
    - assets/ttu-ebook-reader/icons/