name: yuuna
description: A mobile language learning toolkit.

publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_screenutil: ^5.3.1
  flutter_settings_screens: ^0.3.2-null-safety
  package_info_plus: ^1.4.0
  shared_preferences: ^2.0.13
  spaces:
    git:
      url: https://github.com/triskell/spaces
      ref: master

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true