name: yuuna
description: A mobile language learning toolkit.

publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  change_notifier_builder: ^1.1.2
  characters: ^1.2.0
  clipboard: ^0.1.3
  device_info_plus: ^3.2.3
  expandable: ^5.0.1
  external_app_launcher: ^2.0.2
  external_path: ^1.0.1
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_cache_manager: ^3.3.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1
  flutter_process_text: ^1.1.2
  flutter_riverpod: ^1.0.4
  flutter_screenutil: ^5.3.1
  fluttertoast: ^8.0.9
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  http: ^0.13.4
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  json_annotation: ^4.5.0
  json_serializable: ^6.1.5
  kana_kit: ^2.0.0
  marquee: ^2.2.2
  material_floating_search_bar: 
    git:
      url: https://github.com/lrorpilla/material_floating_search_bar
      ref: main
  mecab_dart: ^0.1.3
  network_to_file_image: ^4.0.1
  package_info_plus: ^1.4.0
  path: ^1.8.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  pretty_json: ^2.0.0
  receive_sharing_intent: ^1.4.5
  reorderables: ^0.4.4
  restart_app: ^1.1.0+1
  ruby_text: ^3.0.1
  settings_ui: ^2.0.2
  share_plus: ^4.0.4
  spaces:
    git:
      url: https://github.com/triskell/spaces
      ref: master
  tabbed_view: ^1.12.0
  url_launcher: ^6.0.20
  ve_dart:
    git:
      url: https://github.com/lrorpilla/ve_dart
      ref: c366bb1ae24f6fad4f5c7e3a1efad5f2b8122e58

dependency_overrides:
  fading_edge_scrollview:
      git:
        url: https://github.com/ruslic19/fading_edge_scrollview
        ref: master
  freezed_annotation: ^2.0.3 # Caused by spaces

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^2.2.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/meta/icon.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/meta/icon-android12.png"

flutter:
  uses-material-design: true

  assets:
    - assets/meta/
    - assets/language/japanese/ipadic/