name: yuuna
description: A mobile language learning toolkit.

publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  build_runner: ^2.1.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1
  flutter_riverpod: ^1.0.3
  flutter_screenutil: ^5.3.1
  isar: ^2.2.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  package_info_plus: ^1.4.0
  pretty_json: ^2.0.0
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.13
  spaces:
    git:
      url: https://github.com/triskell/spaces
      ref: master

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/meta/icon.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/meta/icon-android12.png"

flutter:
  uses-material-design: true

  assets:
    - assets/meta/